### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'font-pet-me-128.dat'

### ISSUE THREAD

**Issue by yonjovi** [CoreElectronics/CE-PiicoDev-PyPI#2]
Hi I am getting the following error when running the SSD1306 text display, similar to the example on the Core Electronics website. Could you please tell me what i'm doing wrong?

Traceback (most recent call last):
  File "/home/pi/Desktop/yoled.py", line 7, in <module>
    display.text("Hello, World!", 0, 0, 1)
  File "/home/pi/Desktop/PiicoDev_SSD1306.py", line 139, in text
    fontFile = open("font-pet-me-128.dat", "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'font-pet-me-128.dat'

The code: 

`from PiicoDev_SSD1306 import *
display = create_PiicoDev_SSD1306()

myString = "This is me"
myNumber = 123.3567

display.text("Hello, World!", 0, 0, 1)
display.text(myString, 0, 15, 1)
display.text(str(myNumber), 0, 30, 1)
display.text("{:2f}".format(myNumber), 0, 45, 1)`

**Comment by CoreProduction4** [comment]
Hi yonjovi,

It looks like the `font-pet-me-128.dat` isnt installed alongside the OLED driver, once this is installed all should be working!

Liam
